config/routes.rb
Sensocial::Application.routes.draw do
  devise_for :users

  resources :profils

   root :to => "profils#index"

end

app/models/profil.rb
class Profil < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  					:first_name, :last_name, :profile_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  # GET /profils
  # GET /profils.json
  def index
    @profils = Profil.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profils }
    end
  end

  # GET /profils/1
  # GET /profils/1.json
  def show
    @profil = Profil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profil }
    end
  end

  # GET /profils/new
  # GET /profils/new.json
  def new
    @profil = Profil.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profil }
    end
  end

  # GET /profils/1/edit
  def edit
    @profil = Profil.find(params[:id])
  end

  # POST /profils
  # POST /profils.json
  def create
    @profil = Profil.new(params[:profil])

    respond_to do |format|
      if @profil.save
        format.html { redirect_to @profil, notice: 'Profil was successfully created.' }
        format.json { render json: @profil, status: :created, location: @profil }
      else
        format.html { render action: "new" }
        format.json { render json: @profil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profils/1
  # PUT /profils/1.json
  def update
    @profil = Profil.find(params[:id])

    respond_to do |format|
      if @profil.update_attributes(params[:profil])
        format.html { redirect_to @profil, notice: 'Profil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profils/1
  # DELETE /profils/1.json
  def destroy
    @profil = Profil.find(params[:id])
    @profil.destroy

    respond_to do |format|
      format.html { redirect_to profils_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sensocial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	    <div class="navbar">
    <div class="navbar-inner">
    <a class="brand" href="#">Sensocial</a>
    <ul class="nav">
    <li class="active"><a href="#">Home</a></li>
    <li><%= link_to 'All profils', profils_path %></li>
    <li><a href="#">Link</a></li>
    </ul>
    </div>
    </div>
	<div class="container">

 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<%= yield %>
	</div>
</body>
</html>

app/views/profils/_form.html.erb
<%= form_for(@profil) do |f| %>
  <% if @profil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profil.errors.count, "error") %> prohibited this profil from being saved:</h2>

      <ul>
      <% @profil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profils/edit.html.erb
<h1>Editing profil</h1>

<%= render 'form' %>

<%= link_to 'Show', @profil %> |
<%= link_to 'Back', profils_path %>

app/views/profils/index.html.erb
<div class="page-header">
	<h1>All profils</h1>
</div>
<%= link_to "Post a new Profile", new_profil_path, class:"btn btn-inverse" %>
<% @profils.each do |profil| %>
<div class="profil">
	<strong><%= profil.name %></strong>
	<p><%= profil.content %></p>
	<div class="meta">
		<%= link_to time_ago_in_words(profil.created_at)+" ago", profil %>

		<span class="admin">
			|<%= link_to 'edit', edit_profil_path(profil) %>|
			<%= link_to 'Destroy', profil, method: :delete, data:{confirm:"Are you really wanna delete this profil ?"} %>
		</span>
	</div>
</div>
	<% end %>

app/views/profils/new.html.erb
<h1>New profil</h1>

<%= render 'form' %>

<%= link_to 'Back', profils_path %>

app/views/profils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @profil.name %>
</p>

<p>
  <b>Content:</b>
  <%= @profil.content %>
</p>


<%= link_to 'Edit', edit_profil_path(@profil) %> |
<%= link_to 'Back', profils_path %>